# realizacoes: Quantidade de realizaçoẽs que serão executadas no decorrer do processo.
# epocas: Quantidade de épocas que serão executadas no treinamento do perceptron
# eta: Taxa de aprendizagem do perceptron (Recomendado: 0.1 <= eta <= 0.2)
# base_terino: Percentual da base de dados para treinamento.
# iris_classe: Classe da iris no qual o perceptron irá classificar em detrimento das outras.
#              As classes existentes são: 'Iris-setosa',
#                                         'Iris-versicolor',
#                                         'Iris-virginica'.
# atributos: Atributos que serão utilizados para treinar o perceptron
#            Quais atributos podem ser escolhidos: 0: 'sepal length (cm)',
#                                                  1: 'sepal width (cm)',
#                                                  2: 'petal length (cm)',
#                                                  3: 'petal width (cm)'.
# verb: Exibe todas as informações do melhor e pior resultado.
#            As opções disponíveis sao: 's': Exibir todos os dados
#                                        'n': Não exibir todos os dados
# log: Registra todas as ações em um arquivo, incluindo imagens dos plots em arquivos separados.
#            As opções disponíveis sao: 's': Armazena as informações
#                                        'n': Não armazena as informações

iris_classe: 'Iris-setosa'
realizacoes: 1
epocas: 10
eta: 0.1
base_treino: 0.7
atributos:
  - 0
  - 1
#  - 2
#  - 3
verb: 's'
log: 'n'
curva_aprendizado: 's'