# realizacoes: Quantidade de realizaçoẽs que serão executadas no decorrer do processo.
# epocas: Quantidade de épocas que serão executadas no treinamento do perceptron
# eta: Taxa de aprendizagem do perceptron (Recomendado: 0.1 <= eta <= 0.2)
# base_terino: Percentual da base de dados para treinamento.
# classe: Classe da do problema no qual o perceptron irá classificar em detrimento das outras.
#              As classes existentes são: 'and',
#                                         'or',
#                                         'xor'.
# num_por_classe: Numero de elementos por classe.
# ruido: Valor que será atribuido como ruido no momento em que os padrões estão sendo gerados.
# verb: Exibe todas as informações do melhor e pior resultado.
#            As opções disponíveis sao: 's': Exibir todos os dados
#                                        'n': Não exibir todos os dados
# log: Registra todas as ações em um arquivo, incluindo imagens dos plots em arquivos separados.
#            As opções disponíveis sao: 's': Armazena as informações
#                                        'n': Não armazena as informações

classe: 'or'
realizacoes: 10
epocas: 10
eta: 0.1
base_treino: 0.8
num_por_classe: 100
ruido: 0.15
verb: 's'
log: 'n'